config/routes.rb
Rails.application.routes.draw do
  
  
  root 'public/homes#top'
  
  

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
  
  get 'homes/about' => 'homes#about', as: "about"
  resources :items, only: [:create,:index,:show,:update,:edit,:new]
  
  resources :cart_items,only: [:index,:update,:destroy,:create]
  delete'cart_items/destroy_all'=>'cart_items#destroy_all'
  
  resources :genres, only: [:create, :index,:edit,:update,]
  
  get'customers/infomation/edit'=>'customers#edit'
  patch'customers/infomation/'=>'customers#update'
  get'customers/my_page/' => 'customers#show',as: "my_page"
  get 'customers/unsubscribe'=> 'customers#unsubscribe',as: "unsubscribe"
  patch 'customers/withdraw',as: "withdraw"
  
get'orders/complete'=>'orders#complete',as: "complete"
  resources :orders, only: [:index,:show,:create,:new]
  
  post'orders/confilm'=>'orders#confilm',as: "confilm"
  
  resources :order_details, only: [:update]
  
  resources :addresses

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    namespace :admin do
      get 'admin' => 'homes#top'
      get  'about' =>'homes#about'
      
      resources :items, only: [:index, :show,:new,:create,:edit,:update]
      
      resources :genres, only: [:index,:create,:edit, :update]
    
      resources :customers, only: [:index,:show,:edit, :update]
    
      
      resources :cart_items, only: [:create, :index,:destroy,:update]
      get'cart_items/destroy_all'
      
      resources :orders, only: [:new,:index,:show,:create]
      get'orders/confilm'
      
      resources :addresses, only: [:create,:edit, :index,:destroy,:updat]
    end
  end

 

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
 def full_address
  "〒"+" "+postal_code+" "+address+name
 end
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :customer
 belongs_to :item
 
 def subtotal
  item.with_tax_price * amount
 end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items,dependent: :destroy
  has_many :addresses,dependent: :destroy
   has_many :orders,dependent: :destroy
 
  
  def name
   first_name+last_name
  end
  
  def name_kana
   first_name_kana+last_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :genre
  has_many :order_details
    
  enum genre_status: { sale: true, stop: false }
  
def with_tax_price
 (price * 1.1).floor
end
  
end

app/models/order.rb
class Order < ApplicationRecord
 
 has_many :order_details
 belongs_to :customer

 
 enum payment: { credit_card: 0, transfer: 1 }
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
 belongs_to :order
 belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    
  def index
    @customers = Customer.page(params[:page])
  end

  def show
   @customer = Customer.find(params[:id])
  end

  def edit
   @customer = Customer.find(params[:id])
  end

  def update
   @customer = Customer.find(params[:id])
   @customer.update(customer_params)
  redirect_to admin_customer_path(@customer.id)
  end

  private

 def customer_params
  params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:email,:is_deleted)
 end 
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

 def index
   @genres=Genre.all
   @genre=Genre.new
 end

 def new
  @genre=Genre.new
 end
 
 def create
  genre=Genre.new(genre_params)
  genre.save
  redirect_to admin_genres_path
 end
 
 def edit
  @genre=Genre.find(params[:id])
 end
 
 def update
  genre=Genre.find(params[:id])
  genre.update(genre_params)
  redirect_to admin_genres_path
 end
 
 
 private
 
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
 def top
  @orders = Order.page(params[:page])
 end
 
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
 def index
  @items = Item.page(params[:page])
 end
 
 def new
  @item = Item.new
 end
 
 def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_items_path(params[:id])
 end
 
 def show
  @item = Item.find(params[:id])
  @genre = @item.genre
 end 
  
 def edit
  @item = Item.find(params[:id])
 end
 
 def update
   item = Item.find(params[:id])
   item.update(item_params)
   redirect_to admin_item_path(item.id)  
 end
  
 private
 
 def item_params
  params.require(:item).permit(:name,:introduction,:price,:image,:genre_id,:is_active)
 end 
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

 def complete
 end
 
 def orders
  @oreder = Order.find(params[]) 
 end
 
 def show
  @order = Order.find(params[id])
 end
 
 def index
  @orders = Order.all
 end
    
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
   before_action :configure_permitted_parameters, if: :devise_controller?
  



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:password])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.erb
<h><%= @customer.name %>さんの会員情報編集</h>

<%= form_with model:@customer,url: admin_customer_path,method: :patch do |f| %>
 <table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <%= form_with model:@customer,url: : : do |f| %>
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= f.text_field :last_name_kana %><%=  f.text_field :first_name_kana %></td>
    <tr>
      <td>郵便番号</td>
      <td><%= f.text_field :postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= f.text_field :address %></td>
    </tr>
    <tr>
       <td>電話番号</td>
       <td><%= f.text_field :telephone_number %></td>
    </tr>
    <tr>
       <td>メールアドレス</td>
       <td><%= f.text_field :email %></td>
    </tr>
    <tr>
       <td>会員ステータス</td>
       <td><%= @customer.is_deleted %></td>
    </tr>
  </tbody>
  </table>
  
  <%= f.submit '変更を保存' %>
  
  <% end %>
  
 

app/views/admin/customers/edit.html.erb
<div class = "container">
<dic class = "row">
<div class = "col-md-12">
<h><%= @customer.name %>さんの会員情報編集</h>

<%= form_with model:@customer,url: admin_customer_path,method: :patch do |f| %>
 <table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= f.text_field :first_name, class: "mt-3"%><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%=  f.text_field :first_name_kana, class: "mt-3" %><%= f.text_field :last_name_kana %></td>
    <tr>
      <td>郵便番号</td>
      <td><%= f.text_field :postal_code, class: "mt-3" %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= f.text_field :address, class: "mt-3"%></td>
    </tr>
    <tr>
       <td>電話番号</td>
       <td><%= f.text_field :telephone_number, class: "mt-3" %></td>
    </tr>
    <tr>
       <td>メールアドレス</td>
       <td><%= f.text_field :email, class: "mt-3" %></td>
    </tr>
    <tr>
       <td>会員ステータス</td>
       <td><%= @customer.is_deleted %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td>
       <%= f.radio_button :is_deleted, "true", class: "mt-3" %>
       <%= f.label :is_deleted,"有効" %>
       <%= f.radio_button :is_deleted, "false", class: "mt-3" %>
       <%= f.label :is_deleted,"退会" %>
      </td>
    </tr>
  </tbody>
  </table>
  
  <%= f.submit '変更を保存',class:"btn btn-sm btn-success" %>
  
  <% end %>
  
  </div>
  </div>
  </div>

app/views/admin/customers/index.html.erb
<div class = "container">
<h>会員一覧</h>
</div>

<div class = "container">

<table class="table">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  
  <tbody>
    <% @customers.each do |customer | %>
    <tr>
      <td><%= customer.id  %></td>
      <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
      <td><%=  customer.email %></td>
      
    <% if customer.is_deleted == true %>
      <td>退会</td>
    <% else %>
      <td>有効</td>
    <% end %>
    
    </tr>
    <% end %>
    
  </tbody>
  <%= paginate@customers  %>
</table>

</div>

app/views/admin/customers/show.erb
<h1><% =@customer.name %>さんの会員詳細</h1>

 <table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @customer.last_name %><%= @customer.first_name_kana </td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
    <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
    </tr>
    <tr>
        <td>会員ステータス</td>
        <td><%= @customer.is_deleted %></td>
    </tr>
  </tbody>
  </table>
  
  <%= link_to'編集する',edit_admin_customer_path(customer.id) %>

<%= link_to'注文履歴一覧を見る',admin_customers_path %>

app/views/admin/customers/show.html.erb
<div class = "container">
<div class = "row">
<div class = "col-md-12">
  

<h><%=@customer.name %>さんの会員詳細</h>
 <table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @customer.last_name %><%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
    <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
    </tr>
    <tr>
    <td>会員ステータス</td>
    <% if @customer.is_deleted = false %>
      <td>退会</td>
    <% else %>
      <td>有効</td>
    <% end %></td>
    </tr>
  </tbody>
  </table>
  
  
<div class = "col-4">
<%= link_to'編集する',edit_admin_customer_path(@customer.id),class:"btn btn-sm  btn-success mt-3" %>

<%= link_to'注文履歴一覧を見る',admin_customers_path,class:"btn btn-sm  btn-success mt-3" %>
</div>
</div>
</div>