config/routes.rb
Rails.application.routes.draw do
  
  
  root 'public/homes#top'
  
  

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
  
  get 'homes/about' => 'homes#about', as: "about"
  resources :items, only: [:create,:index,:show,:update,:edit,:new]
  
  resources :cart_items,only: [:index,:update,:destroy,:create]
  delete'cart_items/destroy_all'=>'cart_items#destroy_all'
  
  resources :genres, only: [:create, :index,:edit,:update,]
  
  get'customers/infomation/edit'=>'customers#edit'
  patch'customers/infomation/'=>'customers#update'
  get'customers/my_page/' => 'customers#show',as: "my_page"
  get 'customers/unsubscribe'=> 'customers#unsubscribe',as: "unsubscribe"
  patch 'customers/withdraw',as: "withdraw"
  
get'orders/complete'=>'orders#complete',as: "complete"
  resources :orders, only: [:index,:show,:create,:new]
  
  post'orders/confilm'=>'orders#confilm',as: "confilm"
  
  resources :order_details, only: [:update]
  
  resources :addresses

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    namespace :admin do
      get 'admin' => 'homes#top'
      get  'about' =>'homes#about'
      
      resources :items, only: [:index, :show,:new,:create,:edit,:update]
      
      resources :genres, only: [:index,:create,:edit, :update]
    
      resources :customers, only: [:index,:show,:edit, :update]
    
      
      resources :cart_items, only: [:create, :index,:destroy,:update]
      get'cart_items/destroy_all'
      
      resources :orders, only: [:new,:index,:show,:create]
      get'orders/confilm'
      
      resources :addresses, only: [:create,:edit, :index,:destroy,:updat]
    end
  end

 

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
 def full_address
  "〒"+" "+postal_code+" "+address+name
 end
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :customer
 belongs_to :item
 
 def subtotal
  item.with_tax_price * amount
 end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items,dependent: :destroy
  has_many :addresses,dependent: :destroy
   has_many :orders,dependent: :destroy
 
  
  def name
   first_name+last_name
  end
  
  def name_kana
   first_name_kana+last_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :genre
  has_many :order_details
    
  enum genre_status: { sale: true, stop: false }
  
def with_tax_price
 (price * 1.1).floor
end
  
end

app/models/order.rb
class Order < ApplicationRecord
 
 has_many :order_details
 belongs_to :customer

 
 enum payment: { credit_card: 0, transfer: 1 }
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
 belongs_to :order
 belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

 def index
   @genres=Genre.all
   @genre=Genre.new
 end

 def new
  @genre=Genre.new
 end
 
 def create
  genre=Genre.new(genre_params)
  genre.save
  redirect_to admin_genres_path
 end
 
 def edit
  @genre=Genre.find(params[:id])
 end
 
 def update
  genre=Genre.find(params[:id])
  genre.update(genre_params)
  redirect_to admin_genres_path
 end
 
 
 private
 
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
 def top
  @orders = Order.page(params[:page])
 end
 
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
 def index
  @items = Item.page(params[:page])
 end
 
 def new
  @item = Item.new
 end
 
 def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_items_path(params[:id])
 end
 
 def show
  @item = Item.find(params[:id])
  @genre = @item.genre
 end 
  
 def edit
  @item = Item.find(params[:id])
 end
 
 def update
   item = Item.find(params[:id])
   item.update(item_params)
   redirect_to admin_item_path(item.id)  
 end
  
 private
 
 def item_params
  params.require(:item).permit(:name,:introduction,:price,:image,:genre_id,:is_active)
 end 
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

 def complete
 end
 
 def orders
  @oreder = Order.find(params[]) 
 end
 
 def show
  @order = Order.find(params[id])
 end
 
 def index
  @orders = Order.all
 end
    
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
 
 
  def after_sign_in_path_for(resource)
    admin_admin_path
  end
  
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
   before_action :configure_permitted_parameters, if: :devise_controller?
  



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:password])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-md-12">
            <h3>ジャンル編集</h3>
            
            <p>ジャンル名</p>
            <%= form_with model:@genre,url: admin_genre_path,method: :patch do |f| %>
            <%= f.text_field:name %>
            <%= f.submit '変更を保存',class:"btn btn-sm btn-success" %>
            <% end %>
        
        </div>
    </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="mb-5">ジャンル一覧・追加</h3>
      <%= form_with model:@genre,url: admin_genres_path,method: :post do |f| %>
       <%= f.label :name, "ジャンル名", class: "pr-3" %>
       <%= f.text_field:name,placeholder:"ジャンル名", class: "mr-3" %>
       <%= f.submit'新規登録' , class:"btn btn-sm btn-success" %>
      <% end %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-lg-5">
      <table class="table">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to '編集する',edit_admin_genre_path(genre),class:"btn btn-sm btn-success" %>  </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-7"></div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class = "container">
<div class = "row">
<div class = "col-md-12">
    
<h>商品編集</h>
 <%= form_with model: @item,url: admin_item_path(@item.id),method: :patch do |f| %>

<div class = "row">
 <div class = "col-md-8">
  <%= f.label :image ,"商品画像" %>
  <%= f.file_field :image, accept: "image/*",class:"mb-3 mt-3" %>
 </div>
</div>

<div class = "row">
 <div class = "col-md-8">
  <%= f.label :name ,"商品名" %>
  <%= f.text_field :name ,class:"mb-3 mt-3" %>
 </div>
</div>

<div class = "row">
 <div class = "col-md-8">
  <%= f.label :introduction,"商品説明" %>
  <%= f.text_area :introduction ,class:"mb-3 mt-3" %>
 </div>
</div>

<div class="row">
 <div class = "col-md-8">
  <%= f.label :genre_id, "ジャンル" %>
  <%= f.collection_select :genre_id, Genre.all,:id,:name  ,class:"mb-3 mt-3" %>
 </div>
</div>

<div class = "row">
 <div class = "col-md-8">
  <%= f.label :price ,"税抜価格" %>
  <%= f.text_field :price ,class:"mb-3 mt-3"%>円
 </div>
</div>

<div class = "row">
 <div class = "col-md-8">
  <%= f.label :gunre_status ,"販売ステータス" %>
  <%= f.radio_button :gunre_status, "sale" %>
  <%= f.label :genre_status,"販売中" %>
  <%= f.radio_button :gunre_status, "stop" %>
  <%= f.label :genre_status,"販売停止" %>
 </div>
</div>

</div>

<div class = "row">
 <div class = "col-md-4">
   <%= f.submit '変更を保存',class:"btn btn-sm btn-success" %>
  </div>
 </div>
<% end %>
  </div>
 </div>
</div>

app/views/admin/items/index.erb
<h1>商品一覧</h1>

<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id  %></td>
      
      <td>
      <%= link_to admin_item_path(item.id) do %>
      <%= item.name  %>
      <% end %>
      </td>
      
      <td><%= item.price %></td>
      <td><%= item.genre.name %></td>
      
      <% if item.is_active = true %> 
      <td>販売中</td>
      <% else %>
      <td>販売停止中</td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
  <%= paginate @items %>
</table>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
<h>商品一覧</h>
<%= link_to "商品新規登録",new_admin_item_path,class:"btn btn-sm btn-success ml-" %>
<table class = "table mt-10">
  
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id  %></td>
      
      <td>
      <%= link_to admin_item_path(item.id) do %>
      <%= item.name  %>
      <% end %>
      </td>
      
      <td><%= item.price %></td>
      <td><%= item.genre.name %></td>
      
      <% if item.is_active = true %> 
      <td>販売中</td>
      <% else %>
      <td>販売停止中</td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
  <%= paginate @items %>
</table>
</div>
</div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
    <h>商品新規登録</h>
    
    <%= form_with model:@item,url: admin_items_path,method: :post do |f| %>
    
     <div class="row">
    <div class = "col-md-8">
        <%= f.label :image, "商品画像" %>
        <%= f.file_field :image, accept: "image/*",placeholder:"ファイルを選択" ,class:"mb-3 mt-3" %>
    </div>
    </div>
    
    <div class="row">
    <div class = "col-md-8">
        <%= f.label :name, "商品名" %>
        <%= f.text_field:name ,placeholder:"商品名" ,class:"mb-3" %>
    </div>
    </div>
    
    <div class="row">
    <div class = "col-md-8">
        <%= f.label :introduction, "商品説明" %>
        <%= f.text_area:introduction, placeholder:"ここに説明文を記述します", class:"mb-3" %>
    </div>
    </div>
    
    <div class="row">
    <div class = "col-md-8">
        <%= f.label :genre_id, "ジャンル" %>
        <%= f.collection_select :genre_id, Genre.all,:id,:name ,class:"mb-3" %>
    </div>
    </div>
    
    <div class="row">
    <div class = "col-md-8">
        <%= f.label :price, "税抜価格" %>
        <%= f.text_field:price, placeholder:"1000"  ,class:"mb-3" %>円
    </div>
    </div>
    
    <div class="row">
    <div class = "col-md-8">
    <P>販売ステータス</P>
        <%= f.radio_button :is_active, "sale" %>
        <%= f.label :is_active,"販売中" %>
        <%= f.radio_button :is_active, "stop" %>
        <%= f.label :is_active,"販売停止" %>
    </div>
    </div>
    
    <%= f.submit '新規登録', class:"btn btn-sm btn-success" %>
    
    <% end %>

</div>
</div>
</div>

app/views/admin/items/show.erb
<h1>商品詳細</h1>


<%= image_tag @item.image, size: "200x200" %>



 <table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <td>商品名</td>
      <td><%= @item.name %></td>
    </tr>
    <tr>
      <td>商品説明</td>
      <td><%= @item.introduction %>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= @genre.name %></td>
    <tr>
      <td>税込価格（税抜価格）</td>
      <td><%= (@item.price*1.1).floor %>  <%= "("+@item.price.to_s+")" %></td>
    </tr>
    <tr>
      <td>販売ステータス</td>
      <% if @item.is_active = true %>
      <td>販売中</td>
      <% else %>
      <td>販売停止中</td>
      <% end %>
    </tr>
  </tbody>
  </table>
  
  <%= link_to"編集する",edit_admin_item_path(@item.id) %>

app/views/admin/items/show.html.erb
<div class="container">

<h3>商品詳細</h3>


<div class="row">
<div class="col-md-12 " >
<%= image_tag @item.image, size: "200x200" %>
</div>
</div>

 <table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <td>商品名</td>
      <td><%= @item.name %></td>
    </tr>
    <tr>
      <td>商品説明</td>
      <td><%= @item.introduction %>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= @genre.name %></td>
    <tr>
      <td>税込価格（税抜価格）</td>
      <td><%= (@item.price*1.1).floor %>  <%= "("+@item.price.to_s+")" %></td>
    </tr>
    <tr>
      <td>販売ステータス</td>
      <% if @item.is_active = true %>
      <td>販売中</td>
      <% else %>
      <td>販売停止中</td>
      <% end %>
    </tr>
  </tbody>
  </table>
  
  <%= link_to"編集する",edit_admin_item_path(@item.id),class:"btn btn-sm  btn-success mt-3" %>
  
  
  </div>
  </div>

app/views/admin/orders/index.html.erb
<div class="container">
<div class="row">
<div class="col-lg-12">

<p>注文履歴一覧</p>

<table class="table">
 <thead>
    <tr>
     <th>注文日</th>
     <th>配送先</th>
     <th>注文商品</th>
     <th>支払金額</th>
     <th>注文詳細</th>
    </tr>
 </thead>
 
 <div class = "row">
  <div class ="col-md-12">
 <% @orders.each do |order| %>
 <tbody>
    <tr>
     <td><%=  order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
     
     <td><%= order.address %></td>
     
     <td>
     <% order.order_details.each do |order_detail| %>
     <%= order_detail.item.name %></br>
     <% end %>
     </td>
     
     <td><%= order.billing %></td>
     <td><%= link_to'表示する',order_path(order.id) %></td>
    </tr>
 </tbody>

<% end %>
</table>
 </div>
 </div>
 
</div>
</div>
</div>

app/views/admin/orders/show.html.erb
<div class = "container">
<div class = "row">
<div class = "col-md-12">

<h>注文履歴詳細</h>

<table>
 <thead>
  <tr>
    <th></th>
  </tr>     
 </thead>    
</table>

<tbody>
 <tr>
  <td>購入者</td>
  <td><%= oreder.name %></td>
 </tr>
 <tr>
  <td>注文日</td>
  <td><%= order.created_at %></td>
 </tr>
 <tr>
  <td>配送先</td>
  <td><%= order.address %></td>
 </tr>
 <tr>
  <td>支払方法</td>
  <td><%= order.payment %></td>
 </tr>
</tbody>


<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
    </tr>
  </thead>

  <tbody>
    <% total_price = 0 %>
    <% @cart_items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.item.name %></td>
      <td><%= cart_item.item.price %></td>
      <td><%= cart_item.amount %></td>
      <td><%= cart_item.item.price * cart_item.amount %></td>
    </tr>
    <% total_price += cart_item.item.price * cart_item.amount %>
    <% end %>
  </tbody>
</table>
  
  <table>
    <tbody>
     <tr>      
     <td>商品合計</td>
      <td><%= total_price %></td>
     </tr>
     <tr>
       <td>送料</td>
      <td>800</td>

     </tr>
     <tr>
      <td>請求金額</td>
      <td><%= total_price + 800 %></td>
     </tr>
    </tbody>
  </table>
  
  </div>
  </div>
  </div>