config/routes.rb
Rails.application.routes.draw do
  
  
  root 'public/homes#top'
  
  

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
  
  get 'homes/about' => 'homes#about', as: "about"
  resources :items, only: [:create,:index,:show,:update,:edit,:new]
  
  resources :cart_items,only: [:index,:update,:destroy,:create]
  delete'cart_items/destroy_all'=>'cart_items#destroy_all'
  
  resources :genres, only: [:create, :index,:edit,:update,]
  
  get'customers/infomation/edit'=>'customers#edit'
  patch'customers/infomation/'=>'customers#update'
  get'customers/my_page/' => 'customers#show',as: "my_page"
  get 'customers/unsubscribe'=> 'customers#unsubscribe',as: "unsubscribe"
  patch 'customers/withdraw',as: "withdraw"
  
get'orders/complete'=>'orders#complete',as: "complete"
  resources :orders, only: [:index,:show,:create,:new]
  
  post'orders/confilm'=>'orders#confilm',as: "confilm"
  
  resources :order_details, only: [:update]
  
  resources :addresses

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    namespace :admin do
      get 'admin' => 'homes#top'
      get  'about' =>'homes#about'
      
      resources :items, only: [:index, :show,:new,:create,:edit,:update]
      
      resources :genres, only: [:index,:create,:edit, :update]
    
      resources :customers, only: [:index,:show,:edit, :update]
    
      
      resources :cart_items, only: [:create, :index,:destroy,:update]
      get'cart_items/destroy_all'
      
      resources :orders, only: [:new,:index,:show,:create]
      get'orders/confilm'
      
      resources :addresses, only: [:create,:edit, :index,:destroy,:updat]
    end
  end

 

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
 def full_address
  "〒"+" "+postal_code+" "+address+name
 end
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :customer
 belongs_to :item
 
 def subtotal
  item.with_tax_price * amount
 end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items,dependent: :destroy
  has_many :addresses,dependent: :destroy
   has_many :orders,dependent: :destroy
 
  
  def name
   first_name+last_name
  end
  
  def name_kana
   first_name_kana+last_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :genre
  has_many :order_details
    
  enum genre_status: { sale: true, stop: false }
  
def with_tax_price
 (price * 1.1).floor
end
  
end

app/models/order.rb
class Order < ApplicationRecord
 
 has_many :order_details
 belongs_to :customer

 
 enum payment: { credit_card: 0, transfer: 1 }
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
 belongs_to :order
 belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

 def index
   @genres=Genre.all
   @genre=Genre.new
 end

 def new
  @genre=Genre.new
 end
 
 def create
  genre=Genre.new(genre_params)
  genre.save
  redirect_to admin_genres_path
 end
 
 def edit
  @genre=Genre.find(params[:id])
 end
 
 def update
  genre=Genre.find(params[:id])
  genre.update(genre_params)
  redirect_to admin_genres_path
 end
 
 
 private
 
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
 def top
  @orders = Order.page(params[:page])
 end
 
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
 def index
  @items = Item.page(params[:page])
 end
 
 def new
  @item = Item.new
 end
 
 def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_items_path(params[:id])
 end
 
 def show
  @item = Item.find(params[:id])
  @genre = @item.genre
 end 
  
 def edit
  @item = Item.find(params[:id])
 end
 
 def update
   item = Item.find(params[:id])
   item.update(item_params)
   redirect_to admin_item_path(item.id)  
 end
  
 private
 
 def item_params
  params.require(:item).permit(:name,:introduction,:price,:image,:genre_id,:is_active)
 end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
   before_action :configure_permitted_parameters, if: :devise_controller?
  



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:password])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
         <% if admin_signed_in? %>
         <li  class="nav-item">
           <%= link_to"商品一覧",admin_items_path, class: "nav-link" %>
         </li>
         <li  class="nav-item">
           <%= link_to"会員一覧" ,admin_customers_path, class: "nav-link" %>
         </li>
         <li  class="nav-item">
           <%= link_to"注文履歴一覧", admin_orders_path, class: "nav-link" %>
         </li>
         <li  class="nav-item">
           <%= link_to"ジャンル一覧", admin_genres_path, class: "nav-link" %>
         </li>
          <li  class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li  class="nav-item">
          <% elsif customer_signed_in? %>
          <li  class="nav-item">
            <%= link_to"マイページ",my_page_path(current_customer), class: "nav-link" %>
          </li>
          <li  class="nav-item">
            <%= link_to"商品一覧",items_path, class: "nav-link" %>
          </li>
          <li  class="nav-item">
            <%= link_to"カート",cart_items_path, class: "nav-link" %>
          </li>
          <li  class="nav-item">
             <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
          </li>
          
          <% else %>
          <li  class="nav-item" >
            <%= link_to"About", about_path, class: "nav-link" %>
          </li>
          <li  class="nav-item">
            <%= link_to"商品一覧",admin_items_path, class: "nav-link" %>
          </li>
          <li  class="nav-item">
            <%= link_to "新規登録", new_customer_registration_path , class: "nav-link" %>
          </li>
          <li  class="nav-item", "btn btn-primary">
            <%= link_to "ログイン", new_customer_session_path , class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    </div>
    </div>
  </body>
</html>